Traducción de la página de bienvenida (index.html) y sidebar
DevCMexicoCity/cs50x-2021-latam pull request #1
Opened 2021-01-12 03:29 UTC by mkfnx

Apliqué auto formato del código usando VS Code y traduje la bienvenida y el sidebar.

Realicé algunos cambios en el sidebar para colocar enlaces del grupo de estudio en Discord y redes sociales de DevC CDMX.

Nota: El sidebar debería ser copiada en las otras páginas (si es que no migramos rápido a Jekyll)

2021-01-12 05:11 UTC, tw1ttt3r requested changes
🔥

2021-01-12 05:11 UTC, tw1ttt3r commented on index.html
> +          Históricamente, dos tercios de los estudiantes de CS50 no hand tomado cursos de Computer Sciences anteriormente.
no han

2021-01-12 05:11 UTC, tw1ttt3r commented on index.html
> +          Históricamente, dos tercios de los estudiantes de CS50 no hand tomado cursos de Computer Sciences anteriormente.
Ciencias de la computación

2021-01-14 02:15 UTC, mkfnx commented
Correcciones aplicadas. Gracias, @tw1ttt3r !

2021-01-14 04:37 UTC, tw1ttt3r approved these changes
🔥

2021-01-14 04:38 UTC, tw1ttt3r approved these changes
🔥  🔥

2021-01-14 16:31 UTC, merged